# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-15 10:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boardgames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('img', models.CharField(max_length=1000)),
                ('thumbnail', models.CharField(max_length=1000)),
                ('bggid', models.IntegerField(db_column='bggId', default=0, unique=True)),
                ('minage', models.IntegerField(default=0)),
                ('playingtime', models.IntegerField(default=0)),
                ('minplayers', models.IntegerField(default=0)),
                ('maxplayers', models.IntegerField(default=0)),
                ('yearpublished', models.IntegerField(default=0)),
                ('maxplaytime', models.IntegerField(default=0)),
                ('minplaytime', models.IntegerField(default=0)),
                ('average', models.FloatField(default=0)),
                ('usersrated', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DetailedPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detailed_points', models.IntegerField(default=999999)),
                ('notes', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardgame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Boardgames')),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=256)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('duration', models.IntegerField(default=0)),
                ('boardgame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Boardgames')),
            ],
        ),
        migrations.CreateModel(
            name='Plays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=999999)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Matches')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('img', models.CharField(blank=True, default='img/profile-default.png', max_length=256)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScoringFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(default=0)),
                ('boardgame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Boardgames')),
            ],
        ),
        migrations.AddField(
            model_name='scoringfields',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Templates'),
        ),
        migrations.AddField(
            model_name='scoringfields',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Dictionary'),
        ),
        migrations.AddField(
            model_name='plays',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Profile'),
        ),
        migrations.AddField(
            model_name='friends',
            name='user1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='server.Profile'),
        ),
        migrations.AddField(
            model_name='friends',
            name='user2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='server.Profile'),
        ),
        migrations.AddField(
            model_name='favourites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Profile'),
        ),
        migrations.AddField(
            model_name='detailedpoints',
            name='play',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Plays'),
        ),
        migrations.AddField(
            model_name='detailedpoints',
            name='scoringField',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.ScoringFields'),
        ),
    ]
