# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-16 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_remove_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
