# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20170216_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fav_setting',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='rec_setting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='visibility_group',
            field=models.IntegerField(default=0),
        ),
    ]
