# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_auto_20170408_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='belongstothecategory',
            name='boardgame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Boardgames'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='designer',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='isdesignedby',
            name='boardgame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Boardgames'),
        ),
        migrations.AlterField(
            model_name='ispublishedby',
            name='boardgame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Boardgames'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
