# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-09 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_auto_20170203_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='detailedpoints',
            name='template',
        ),
        migrations.RemoveField(
            model_name='templates',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='templates',
            name='word',
        ),
        migrations.AddField(
            model_name='templates',
            name='vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='img',
            field=models.CharField(blank=True, default='img/profile-default.png', max_length=256),
        ),
        migrations.AddField(
            model_name='scoringfields',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Templates'),
        ),
        migrations.AddField(
            model_name='scoringfields',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Dictionary'),
        ),
    ]
