# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-09 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_auto_20170209_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailedpoints',
            name='scoringField',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='server.ScoringFields'),
        ),
    ]
