# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_belongstothefamily_isexpansionof'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayedExpansions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardgame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Boardgames')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Matches')),
            ],
        ),
    ]
