# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-09 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_detailedpoints_scoringfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailedpoints',
            name='scoringField',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.ScoringFields'),
        ),
    ]
