# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-28 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_plays_turn'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='isexpansionof',
            unique_together=set([('boardgame1', 'boardgame2')]),
        ),
    ]
